'use client'

import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import type { ExtraHoursRequestWithTeacher } from '@/types/database'
import { addExtraHours, decideExtraHours } from './actions'

const fmt = (m: number) => `${Math.floor(m / 60)}:${String(m % 60).padStart(2, '0')}`

export default function ExtraHoursAdminClient({ initialRequests, teachers }: { initialRequests: ExtraHoursRequestWithTeacher[]; teachers: { id: string; name: string }[] }) {
  const [open, setOpen] = useState(false)
  const [busy, startTransition] = useTransition()
  const [error, setError] = useState('')
  const [addUnitMinutes, setAddUnitMinutes] = useState(45)
  const [addQuantity, setAddQuantity] = useState(1)
  const [edits, setEdits] = useState<Record<string, { unitMinutes: number; quantity: number; note: string }>>({})
  const router = useRouter()
  const pending = initialRequests.filter(r => r.status === 'pending')
  const history = initialRequests.filter(r => r.status !== 'pending')

  function editFor(r: ExtraHoursRequestWithTeacher) {
    if (edits[r.id]) return edits[r.id]
    const unitMinutes = r.minutes % 45 === 0 ? 45 : r.minutes % 60 === 0 ? 60 : 30
    return { unitMinutes, quantity: Math.max(1, Math.round(r.minutes / unitMinutes)), note: '' }
  }
  function decide(r: ExtraHoursRequestWithTeacher, status: 'approved' | 'rejected') { const e = editFor(r); setError(''); startTransition(async () => { const result = await decideExtraHours(r.id, status, e.unitMinutes * e.quantity, e.note); if (result.error) return setError(result.error); router.refresh() }) }
  function add(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; setError(''); startTransition(async () => { const result = await addExtraHours(new FormData(form)); if (result.error) return setError(result.error); form.reset(); setAddUnitMinutes(45); setAddQuantity(1); setOpen(false); router.refresh() }) }

  return <main className="px-4 py-5 max-w-2xl mx-auto flex flex-col gap-5" dir="rtl">
    <div className="flex justify-between items-center"><p className="text-sm font-bold text-gray-700">בקשות ממתינות ({pending.length})</p><button onClick={() => setOpen(!open)} className="bg-violet-600 text-white px-4 py-2 rounded-xl text-sm font-bold">+ הוספה למורה</button></div>
    {open && <form onSubmit={add} className="bg-violet-50 border border-violet-200 rounded-2xl p-4 grid grid-cols-2 gap-3"><select name="teacher_id" required defaultValue="" className="col-span-2 border rounded-xl px-3 py-2 text-sm"><option value="" disabled>בחירת מורה</option>{teachers.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select><input name="work_date" type="date" required className="border rounded-xl px-3 py-2 text-sm"/><select name="activity_type" required defaultValue="" className="border rounded-xl px-3 py-2 text-sm"><option value="" disabled>סוג פעילות</option><option>ישיבת צוות</option><option>חזרה</option><option>אירוע</option><option>עבודה מנהלתית</option><option>אחר</option></select><div className="col-span-2 bg-white border border-violet-200 rounded-2xl p-3"><p className="text-xs font-semibold text-violet-700 mb-2">אורך כל יחידה</p><div className="grid grid-cols-3 gap-2">{[30,45,60].map(value => <button key={value} type="button" onClick={() => setAddUnitMinutes(value)} className={`py-2 rounded-xl text-sm font-bold border ${addUnitMinutes === value ? 'bg-violet-600 border-violet-600 text-white' : 'border-violet-200 text-violet-700'}`}>{value === 60 ? 'שעה' : `${value} דקות`}</button>)}</div><input type="hidden" name="unit_minutes" value={addUnitMinutes}/><input type="hidden" name="quantity" value={addQuantity}/><p className="text-xs font-semibold text-violet-700 mt-4 mb-2">כמה יחידות?</p><div className="flex items-center justify-center gap-5"><button type="button" onClick={() => setAddQuantity(q => Math.max(1, q - 1))} className="w-10 h-10 rounded-full bg-violet-100 text-violet-700 text-xl font-bold">−</button><span className="text-2xl font-bold min-w-8 text-center">{addQuantity}</span><button type="button" onClick={() => setAddQuantity(q => Math.min(32, q + 1))} className="w-10 h-10 rounded-full bg-violet-600 text-white text-xl font-bold">+</button></div><p className="mt-3 bg-violet-50 rounded-xl px-3 py-2 text-center text-sm font-bold text-violet-800">{addQuantity} × {addUnitMinutes} דקות = {fmt(addQuantity * addUnitMinutes)} שעות</p></div><textarea name="note" placeholder="פירוט" className="col-span-2 border rounded-xl px-3 py-2 text-sm resize-none"/>{error && <p className="col-span-2 text-xs text-red-600">{error}</p>}<button disabled={busy} className="bg-violet-600 text-white rounded-xl py-2 text-sm font-bold">הוסף ואשר</button><button type="button" onClick={() => setOpen(false)} className="bg-white border rounded-xl py-2 text-sm font-bold text-gray-500">ביטול</button></form>}
    {!pending.length && <p className="text-sm text-gray-400 text-center py-6">אין בקשות שממתינות לאישור</p>}
    {pending.map(r => { const e = editFor(r); return <div key={r.id} className="bg-white border border-amber-100 shadow-sm rounded-2xl p-4"><div className="flex justify-between"><span className="font-bold text-gray-800">{r.teachers?.name ?? 'מורה'}</span><span className="text-xs bg-amber-100 text-amber-700 px-2 py-1 rounded-full font-bold">ממתין</span></div><p className="text-sm mt-2">{new Date(r.work_date + 'T12:00:00').toLocaleDateString('he-IL')} · {r.activity_type}</p>{r.note && <p className="text-xs text-gray-500 mt-1">{r.note}</p>}<div className="mt-3 bg-violet-50 rounded-xl p-3"><div className="grid grid-cols-3 gap-2">{[30,45,60].map(value => <button key={value} type="button" onClick={() => setEdits(v => ({...v, [r.id]: {...e, unitMinutes: value}}))} className={`py-1.5 rounded-lg text-xs font-bold border ${e.unitMinutes === value ? 'bg-violet-600 text-white border-violet-600' : 'bg-white text-violet-700 border-violet-200'}`}>{value === 60 ? 'שעה' : `${value} דק׳`}</button>)}</div><div className="flex items-center justify-center gap-4 mt-3"><button type="button" onClick={() => setEdits(v => ({...v, [r.id]: {...e, quantity: Math.max(1, e.quantity - 1)}}))} className="w-9 h-9 rounded-full bg-white text-violet-700 font-bold">−</button><span className="font-bold text-lg">{e.quantity} יחידות</span><button type="button" onClick={() => setEdits(v => ({...v, [r.id]: {...e, quantity: Math.min(32, e.quantity + 1)}}))} className="w-9 h-9 rounded-full bg-violet-600 text-white font-bold">+</button></div><p className="text-center text-xs font-bold text-violet-800 mt-2">סה״כ: {fmt(e.unitMinutes * e.quantity)} שעות</p></div><input placeholder="הערת מנהל (אופציונלי)" value={e.note} onChange={x => setEdits(v => ({...v, [r.id]: {...e, note: x.target.value}}))} className="w-full border rounded-lg px-3 py-2 text-sm mt-2"/>{error && <p className="text-xs text-red-600 mt-2">{error}</p>}<div className="flex gap-2 mt-3"><button disabled={busy} onClick={() => decide(r, 'approved')} className="flex-1 bg-emerald-500 text-white rounded-xl py-2 text-sm font-bold">אשר</button><button disabled={busy} onClick={() => decide(r, 'rejected')} className="flex-1 bg-red-50 text-red-600 rounded-xl py-2 text-sm font-bold">דחה</button></div></div> })}
    {!!history.length && <><p className="text-xs font-bold text-gray-400 mt-2">היסטוריה</p>{history.map(r => <div key={r.id} className="bg-gray-50 border rounded-2xl p-4 flex justify-between gap-3"><div><p className="text-sm font-bold">{r.teachers?.name ?? 'מורה'} · {r.activity_type}</p><p className="text-xs text-gray-500">{new Date(r.work_date + 'T12:00:00').toLocaleDateString('he-IL')} · {r.source === 'admin' ? 'נוסף על ידי המנהל' : 'בקשת מורה'}</p></div><div className="text-left"><p className="font-bold text-violet-700">{fmt(r.minutes)}</p><span className={`text-xs font-bold ${r.status === 'approved' ? 'text-emerald-600' : 'text-red-500'}`}>{r.status === 'approved' ? 'אושר' : 'נדחה'}</span></div></div>)}</>}
  </main>
}
